"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Minikube Docker.py']
DATA_FILES = []
OPTIONS = {"plist": { "CFBundleIdentifier": "com.coredigital.minikubedocker", "CFBundleVersion": "1.0.0" }}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
